version: "3"
services:
  db:
    image: postgres:10.3
    container_name: magnito
    ports:
      - "${PGPORT}:5432"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
